language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - redis


# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

before_deploy:
  - zip -r pjh-server *
  - mkdir -p deploy
  - mv pjh-server.zip deploy/pjh-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-s3 # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-s3 # S3 버킷
    key: pjh-server.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: pjh-server # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: pjh-server # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true


after_success:
  - ./gradlew jacocoTestReport coveralls


before_install:
  - chmod +x gradlew

# CI 실행 완료시 메일 알림
notifications:
  email:
    recipients:
      - epictroll2018@gmail.com