language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - redis


# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

after_success:
  - ./gradlew jacocoTestReport coveralls


before_install:
  - chmod +x gradlew

# CI 실행 완료시 메일 알림
notifications:
  email:
    recipients:
      - epictroll2018@gmail.com