language: java
jdk:
  - openjdk8

branches:
  only:
    - master

services:
  - redis


# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

after_success:
  - ./gradlew jacocoTestReport coveralls


before_install:
  - chmod +x gradlew
  - wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
  - unzip -qq gradle-5.2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

# CI 실행 완료시 메일 알림
notifications:
  email:
    recipients:
      - epictroll2018@gmail.com